### ISSUE TITLE
Satip discovery or command line Options 

### ISSUE THREAD

**Issue by DeathHarmony** [GauthamVarmaK/addon-tvheadend#111]
# Problem/Motivation

Satip discovery doesn't work and I can't find an option to give  Command line Options like --satip_xml

**Comment by matze308** [comment]
Hi, i have the same problem. Found no option to give command line options

**Comment by DeathHarmony** [comment]
I found a way. Put this in init commands
```
echo "$(cat /etc/services.d/tvheadend/run) --satip_xml
    http://10.0.0.4:49000/satipdesc.xml" >/etc/services.d/tvheadend/run
```
