### ISSUE TITLE
Submit to official community addon list?

### ISSUE THREAD

**Issue by MatthiasLohr** [GauthamVarmaK/addon-tvheadend#122]
# Problem/Motivation

Home Assistant has an official repository for community addons. I'm wondering why this (very useful and nice!) addon is in an extra repository and not part of the community addon list (https://addons.community/)?

## Expected behavior

The addon should be listed and be part of the HA community addon list.

## Actual behavior

Currently, it's not in that list.

**Comment by bf8392** [comment]
+1

**Comment by MatthiasLohr** [comment]
@GauthamVarmaK, any opinion on this?
