### ISSUE TITLE
can't record

### ISSUE THREAD

**Issue by niwi-hh** [GauthamVarmaK/addon-tvheadend#176]
# Problem/Motivation

I would like to record tv-shows with TVHeadend on my Intel-NUC with Home Assistant.

## Expected behavior

TVHeadend should be able to record with default settings.

## Actual behavior

If I try to record something, TVHeadend freezes and needs a restart. In the log the last entry is:
`2022-11-28` 22:40:00.736 [  ERROR] dvr: Recording error: "Time-2022-11-28_22:40": Unable to create file

## Steps to reproduce

Just start any timer for a tv-show. 

## Proposed changes

The permissions unter /config/tvheadend/recordings/ might be wrong or the user runing TVHeadend might needmore rights. I  don't know how to check and change this in Home Assistant. The addon should set those settings correctly by default or if not possible, the addon should include instructions how to change those settings.

[log.txt.txt](https://github.com/GauthamVarmaK/addon-tvheadend/files/10107760/log.txt.txt)

**Comment by niwi-hh** [comment]
Please un-stale. My bug report is just one month old.

**Comment by HahnBenjamin** [comment]
@niwi-hh I faced the same problem. In the _Digital Video Recorder Profiles_ change the `Filename character set` from ASCII to UTF-8. You need to enable the **Expert** view level to see the setting.

**Comment by niwi-hh** [comment]
> @niwi-hh I faced the same problem. In the _Digital Video Recorder Profiles_ change the `Filename character set` from ASCII to UTF-8. You need to enable the **Expert** view level to see the setting.

This solved my problem. Thanks a lot!  However, I leave this ticket open since the solution should either be part of the documentation or be the default setting. I assume all installations with other languages than English have this problem. If utf8 would be the default, everything should still be fine for systems with English as default.
