### ISSUE TITLE
hdhomerun

### ISSUE THREAD

**Issue by wired-dev** [GauthamVarmaK/addon-tvheadend#203]
i cant seem to get it to detect my hdhomerun tunner

**Comment by miikka75** [comment]
I am having same problem. It's related to problem solved by this pull request to TVH: https://github.com/tvheadend/tvheadend/pull/1250
@GauthamVarmaK  Any chance of updating TVH to a version that includes this fix?
Other option would be to allow running this add-on (docker container) with --net=host option. I guess this may be possible with [host_network](https://developers.home-assistant.io/docs/add-ons/configuration/#optional-configuration-options) option.
