### ISSUE TITLE
Please upgrade the TVheadend version

### ISSUE THREAD

**Issue by JAAlperin** [GauthamVarmaK/addon-tvheadend#283]
# Problem/Motivation

I'm running TVheadend 4.3-2266~ge02e812ee on Ubuntu installed per https://cgomesu.com/blog/Tvhlink/#host-installation-1 on a pi4.  My single automatic channel definition produced 57 mux and 57 services.

I want to move TVheadend to the Home Assistant add-on, but it is based on 4.2.8 (which has a copyright date of 2017), and the automatic channel scan produces 57 mux and 0 services.

## Expected behavior
Channel scan results would be the same

## Actual behavior
Channel scan results are different

## Steps to reproduce
Create an automatic channel for the url:
https://raw.githubusercontent.com/cgomesu/tvhlink/master/m3u/youtube.m3u
and scan it

## Proposed changes
As the channel definition inputs are different for the two releases, I suggest upgrading the add-on to the latest version of TVheadend to see if that will resolve the different behaviors.

**Comment by cbourne142857** [comment]
I'm in a similar situation - the general advice seems to be to run 4.3, at least until 4.4 stable comes out.

https://tvheadend.org/p/downloads
