### ISSUE TITLE
Failed to uninstall add-on in versions<=v1.1.0

### ISSUE THREAD

**Issue by sbs20** [GauthamVarmaK/addon-tvheadend#29]
Hi. I receive the following error when trying to uninstall the add-on. This is installed on:
* HAOS 6.2
* supervisor-2021-06.8
* core-2021.8.8

If you have any guidance on how to uninstall then that would be great - thank you!

![image](https://user-images.githubusercontent.com/3080753/130236492-05337443-857a-4a4b-9c29-8c49a5441f02.png)

**Comment by GauthamVarmaK** [comment]
If my guess is right, you may be running a version older than v1.1.0 of the addon and trying to update/delete.

Kindly follow the following steps:
- Stop the TVHeadend Addon
- Install the Portainer Addon
- Delete the TVHeadend container from the list (in Portainer)
- Reboot the host system
- Now the addon must be greyed out
- Click on the addon, and click Uninstall
- The Addon should now disappear, may show an error saying the image doesn't exit or something.

You may reinstall the addon again and your files & settings will persist (`/config/tvheadend/` is used to store config, delete that folder as well for a complete reset of TVHeadend) 

If this solves your issue, will go ahead and close this issue.

**Comment by sbs20** [comment]
Thank you so much for the advice - I will try it over the weekend and report back!

I can't get a screen shot right now, but it's definitely v1.1.0 - but you're correct, I'm trying to remove it.

**Comment by GauthamVarmaK** [comment]
Thanks for letting me know. The issue has now been fixed in [v1.1.1 ](https://github.com/GauthamVarmaK/addon-tvheadend/releases/tag/v1.1.1)

U may try upgrading to v1.1.1 since you are on v1.1.0 and then clicking on Uninstall!!

The above guide is from now applicable for versions <=v1.1.0 and recommended during an upgrade from <=v1.0.4 to any further higher version. Adding note, about the same as well.

**Comment by sbs20** [comment]
The upgrade and uninstall worked. Thanks so much for a quick turnaround.

(Good work with the add-on too, I already have a dedicated tvh server, so don't really need this)
