### ISSUE TITLE
Service/Server does not start on Raspberry Pi 2 or 4

### ISSUE THREAD

**Issue by harryberlin** [GauthamVarmaK/addon-tvheadend#335]
# Problem/Motivation

> Service/Server does not start on Raspberry Pi 2 or 4

## Expected behavior

> Server should start

## Actual behavior

> HA shows, that addon is started [green dot]
> 
> ![image](https://github.com/user-attachments/assets/800bf897-c9f5-48bc-80e0-c2e1ffa1d2b9)
> 
> but interface is not available
> 
> ![image](https://github.com/user-attachments/assets/2ee3e01d-01b5-410d-bbeb-ee32c3771ee1)
> 

## Steps to reproduce

> fresh HA image from webside and steps to get tvheadend addon

## Proposed changes

> Would be great to get instruction to get it working

**Comment by Avishadur** [comment]
I have the same on other hardware as well.
I would assume if OP checks logs, they'll find the addon restarting on loop and getting stuck setting something up, in my case webgrab+

Is there any way to either ignore webgrab for now or fix this little loop?

[16:31:22] INFO: [Webgrab+] Installing Webgrab+.
Connecting to webgrabplus.com (213.126.50.203:80)
wget: server returned error: HTTP/1.1 403 Forbidden
