### ISSUE TITLE
Sat-IP Server in the same network not detected 

### ISSUE THREAD

**Issue by averagenormalguy** [GauthamVarmaK/addon-tvheadend#71]
Problem/Motivation

Sat-IP Server not found 

## Expected behavior

Sat-IP Server in the same network should be found automatically, as it does on the Synology Packet (same network).

## Actual behavior

Sat-IP Server is not found (under tv adapters )

## Steps to reproduce

-

## Proposed changes

Maybe the container is not allowed to detect devices form the network.

**Comment by GauthamVarmaK** [comment]
Does this work on the `linuxserver` images?

If yes, attach some screenshots of it being discovered in portainer/on the TVHeadend.
Also if you could elaborate on the discovery mechanism, or share some logs if u spot anything interesting, may help!

If it doesn't work there then it is probably a limitation of docker implementation.

Also if the discovery and communication is purely network based, modifying the Addon to run on host network may work, but also means we need to secure the addon further along with strong password setup by every user to avoid a weak point in the network.

**Comment by jezyjay** [comment]
I have the same issue. I have read, that the network type of the container should be host? The standard is bridge. What network type do you use for the addon?
